ProMotos/urls.py
# -*- encoding: utf-8 -*-
from django.contrib import admin
from django.conf.urls import include, url
from ProMotos import settings
admin.autodiscover()

urlpatterns = [
	url(r'^admin/', include(admin.site.urls)),
	url(r'', include('apps.home.urls',namespace='inicio')),
	url(r'', include('apps.cuenta.urls',namespace='cuenta')),
    url(r'', include('apps.cotizacion.urls',namespace='cotizacion')),
    url(r'', include('apps.cliente.url',namespace='cliente')),
    url(r'', include('apps.empleado.url',namespace='empleado')),
    url(r'', include('apps.repuesto.url',namespace='repuesto')),
    url(r'', include('apps.sucursal.url',namespace='sucursal')),
    url(r'', include('apps.motocicleta.url',namespace='motocicleta')),
    url(r'', include('apps.venta.url',namespace='venta')),
    url(r'', include('apps.proveedor.url',namespace='proveedor')),
    url(r'', include('apps.reporte.url',namespace='reporte')),
    url(r'', include('apps.orden_de_trabajo.url',namespace='orden_de_trabajo')),
    url(r'', include('apps.cotizacion_orden_de_trabajo.url',namespace='cotizacion_orden_de_trabajo')),
    url(r'', include('apps.factura_orden_de_trabajo.url',namespace='factura_orden_de_trabajo')),
    url(r'', include('apps.movil.url',namespace='movil')),
]

apps/cotizacion/urls.py
# -*- encoding: utf-8 -*-

from django.conf.urls import include, url
from .forms import CrearCotizacion, ActualizarCotizacion
from .views import ListaCotizaciones
from .views import PdfCreateView
urlpatterns = [

    #url que redirecciona a la pagina de creacion de cotizaciones
    url(r'^cotizacion/crear$', CrearCotizacion.as_view(), name='crear'),
	url(r'^cotizacion/(?P<pk>\d+)/$', ActualizarCotizacion.as_view(), name='actualizar'),
	url(r'^cotizacion/listado$', ListaCotizaciones.as_view(), name='listar'),
	url(r'^cotizacion/PDF/(?P<pk>\d+)/$', PdfCreateView.as_view(), name='pdf'),
]

apps/cotizacion/models.py
# -*- encoding: utf-8 -*-
from django.db import models
import datetime
from apps.empleado.models import Empleado
from apps.cliente.models import Cliente
from apps.motocicleta.models import Motocicleta


# Forma de pago en que se realiza la compra
EFECTIVO = 'Efectivo'
#solo se encuentra habilitado la de efectivo
forma_pago_choices = (
	(EFECTIVO, 'Efectivo'),
)

#
class Cotizacion(models.Model):
	"""Define la organizacion del los datos de una cotizacion en la base de datos."""

	#Empleado que realiza la cotizacion, relacion uno a muchos
	empleado= models.ForeignKey(Empleado,default=None)
	#Cliente que solicita la cotizacion, relacion uno a muchos
	cliente= models.ForeignKey(Cliente,default=None)
	#Motocicleta que va a ser cotizada, relacion uno a muchos
	moto= models.ForeignKey(Motocicleta,default=None)
	#Fecha en que se realiza la cotizacion
	fecha=models.DateField(auto_now_add=True)
	#Fecha de vencimiento de la cotizacion
	fecha_vencimiento=models.DateField()
	#Forma de pago en la que se realiza la cotizacion
	forma_pago = models.CharField(max_length=20,choices=forma_pago_choices, default=EFECTIVO)
	#Estado de la cotizacion, Activa/inactiva
	habilitado = models.BooleanField(default = True)

	#Permite hacer modificaciones agregadas a la representacion del modelo
	class Meta:
		ordering = ['fecha']
		verbose_name_plural = "Cotizaciones"

	#Permite determinar una representacion en string del objeto
	def __str__(self):
		return self.cliente.nombre

apps/cotizacion/forms.py
# -*- encoding: utf-8 -*-
from django.core.urlresolvers import reverse_lazy, reverse
from django import forms
from django.http import HttpResponse
from django.http import HttpResponseRedirect
from django.shortcuts import render_to_response
from django.template import RequestContext
from django.views.generic.edit import CreateView, UpdateView
from .models import Cotizacion
from apps.cliente.models import Cliente
from apps.empleado.models import Empleado
from apps.motocicleta.models import Motocicleta
from django.contrib import messages


class CrearCotizacion(CreateView):
    fecha_vencimiento=forms.DateField(
        widget=forms.widgets.DateInput(format="%y-%m-%d"))
    model = Cotizacion
    fields = [ 'cliente', 'vehiculo', 'fecha_vencimiento', 'forma_pago']



    def get_context_data(self,**kwargs):

        context = super(CrearCotizacion,self).get_context_data(**kwargs)
        context['search_button_text'] = 'Completar Formulario'

        clientes = Cliente.objects.all()
        context['lista_clientes'] = clientes

        motocicletas = Motocicleta.objects.all()
        context['motocicletas'] = motocicletas

        return context

    def post(self, request, *args, **kwargs):

        empleado = Empleado.objects.get(user_id=self.request.user.id)
        cliente = Cliente.objects.get(pk=request.POST["cliente"])
        motocicleta = Motocicleta.objects.get(pk=request.POST["motocicleta"])
        forma_pago = request.POST["forma_pago"]
        fecha_vencimiento=  request.POST["fecha_vencimiento"]
        cotizacion = Cotizacion(empleado = empleado, cliente = cliente, motocicleta = motocicleta, fecha_vencimiento=fecha_vencimiento,forma_pago = forma_pago)
        cotizacion.save()
        context = {'cotizacion':cotizacion}
        return render_to_response(
            'cotizacion/cotizacionPDF.html',
            context,
            context_instance=RequestContext(request)
        )



class ActualizarCotizacion(UpdateView):
    model = Cotizacion
    fields = ['empleado', 'cliente', 'motocicleta', 'fecha','fecha_vencimiento', 'forma_pago']
    def get_success_url(self):
        messages.info(self.request,"Cotización creada con exito!!!")
        return  reverse_lazy('cotizacion:listar')

apps/cotizacion/views.py
# -*- encoding: utf-8 -*-

from django.views.generic import ListView
from .models import Cotizacion
from django.shortcuts import render_to_response
from django.template import RequestContext
from django.views.generic import TemplateView

class ListaCotizaciones(ListView):
	model = Cotizacion
	context_object_name = 'lista_cotizaciones'



class PdfCreateView(TemplateView):
	def get(self,request,*args,**kwargs):
		cotizacion= Cotizacion.objects.get(id=kwargs['pk'])
		context = {'cotizacion':cotizacion}

		return render_to_response(
			'cotizacion/cotizacionPDF.html',
			context,
			context_instance=RequestContext(request)
		)

apps/cotizacion/templates/cotizacion/includes/crear.html
{% extends "base.html" %}
{% load staticfiles %}

{# Load the tag library #}
{% load bootstrap3 %}

{# Load CSS and JavaScript #}
{% bootstrap_css %}
{% bootstrap_javascript %}

{# Display django.contrib.messages as Bootstrap alerts #}
{% bootstrap_messages %}

<!-- css auxiliar -->
{% block custom-css %}
	<!-- ================== BEGIN PAGE LEVEL STYLE ================== -->
	<link href="{% static 'color_admin/assets/plugins/bootstrap-wizard/css/bwizard.min.css' %}" rel="stylesheet" />
	<!-- Para gestionar Fechas -->
	<link href="{% static 'color_admin/assets/plugins/bootstrap-datepicker/css/datepicker.css'%}" rel="stylesheet" />
 	<link href="{% static 'color_admin/assets/plugins/bootstrap-datepicker/css/datepicker3.css'%}" rel="stylesheet" />
 	<!-- fin Para gestionar Fechas -->

	<!-- ================== END PAGE LEVEL STYLE ================== -->
{% endblock %}

<!-- Enacabezado de la seccion -->
{% block content %}
	<!-- begin #page-container -->
	<div id="page-container" class="fade page-sidebar-fixed page-header-fixed">
		
		<!-- begin #header -->
		{% include "includes/header.html" %}
		<!-- end #header -->
		
		<!-- begin #sidebar -->
		{% include "includes/sidebar.html" %}
		<!-- end #sidebar -->
		
		<!-- begin #content -->
		<div id="content" class="content">
			<!-- begin page-header -->
			<h1 class="page-header">Cotizaciones</h1>
			<!-- end page-header -->
			
			<!-- begin indicators -->
			{% include "includes/indicadores.html"%}
			<!-- end indicators -->
						
			<!-- begin row -->
			<div class="row">

				<!-- begin col-8 -->
				<div class="col-md-8">
					<!-- begin col-12 -->
				    <div class="col-md-12">
				        <!-- begin panel -->
	                    <div class="panel panel-inverse">
	                        <div class="panel-heading">
	                            <div class="panel-heading-btn">
	                                <a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-default" data-click="panel-expand"><i class="fa fa-expand"></i></a>
	                                <a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-success" data-click="panel-reload"><i class="fa fa-repeat"></i></a>
	                                <a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-warning" data-click="panel-collapse"><i class="fa fa-minus"></i></a>
	                                <a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-danger" data-click="panel-remove"><i class="fa fa-times"></i></a>
	                            </div>
	                            <h4 class="panel-title">Nueva cotización</h4>
	                        </div>
	                        <div class="panel-body">
	                        	{# Display a form #}
	                        	{# the enctype="multipart/form-data" is necessary to upload files#}
	                            <form action="{% url 'cotizacion:crear' %}" method="POST" enctype="multipart/form-data"> {% csrf_token %}
	                            {% bootstrap_form form %}
									<div id="wizard">
										
										<button type="submit" class="btn btn-inverse"><i class="fa fa-cog"></i> Generar</button>
										
										
									</div>
								</form>
	                        </div>
	                    </div>
	                    <!-- end panel -->
	                </div>
	                <!-- end col-12 -->
	            </div>
	            <!-- end col-8 -->

				<!-- begin col-4 -->
				<div class="col-md-4">
				{% include "includes/calendario.html" %}
				</div>
				<!-- end col-4 -->
			</div>
			<!-- end row -->
		</div>
		<!-- end #content -->
	
		
		<!-- begin scroll to top btn -->
		<a href="javascript:;" class="btn btn-icon btn-circle btn-success btn-scroll-to-top fade" data-click="scroll-top"><i class="fa fa-angle-up"></i></a>
		<!-- end scroll to top btn -->
	</div>
	<!-- end page container -->
{% endblock %}

<!-- JavaScript auxiliar -->
{% block custom-js %}
	<!-- ================== BEGIN PAGE LEVEL JS ================== -->
	<script src="{% static 'color_admin/assets/plugins/bootstrap-wizard/js/bwizard.js' %}"></script>
	<script src="{% static 'color_admin/assets/js/form-wizards.demo.min.js' %}"></script>
	<script src="{% static 'color_admin/assets/js/apps.min.js' %}"></script>
	
	<!-- Para gestionar Fechas -->
	<script src="{% static 'color_admin/assets/js/bootstrap-datepicker.js' %}"></script>

	<script>
		$(document).ready(function(){
			$('#id_fecha').datepicker({todayHighlight:true,autoclose:true});
			$('#id_fecha_vencimiento').datepicker({todayHighlight:true,autoclose:true});

		});
	</script>
	<!-- fin Para gestionar Fechas -->

	<!-- ================== END PAGE LEVEL JS ================== -->
{% endblock %}