ProMotos/urls.py
# -*- encoding: utf-8 -*-
from django.contrib import admin
from django.conf.urls import include, url
from ProMotos import settings
admin.autodiscover()

urlpatterns = [
	url(r'^admin/', include(admin.site.urls)),
	url(r'', include('apps.home.urls',namespace='inicio')),
	url(r'', include('apps.cuenta.urls',namespace='cuenta')),
    url(r'', include('apps.cotizacion.urls',namespace='cotizacion')),
    url(r'', include('apps.cliente.url',namespace='cliente')),
    url(r'', include('apps.empleado.url',namespace='empleado')),
    url(r'', include('apps.repuesto.url',namespace='repuesto')),
    url(r'', include('apps.sucursal.url',namespace='sucursal')),
    url(r'', include('apps.motocicleta.url',namespace='motocicleta')),
    url(r'', include('apps.venta.url',namespace='venta')),
    url(r'', include('apps.proveedor.url',namespace='proveedor')),
    url(r'', include('apps.reporte.url',namespace='reporte')),
    url(r'', include('apps.orden_de_trabajo.url',namespace='orden_de_trabajo')),
    url(r'', include('apps.cotizacion_orden_de_trabajo.url',namespace='cotizacion_orden_de_trabajo')),
    url(r'', include('apps.factura_orden_de_trabajo.url',namespace='factura_orden_de_trabajo')),
    url(r'', include('apps.movil.url',namespace='movil')),
]

apps/cotizacion/urls.py
# -*- encoding: utf-8 -*-

from django.conf.urls import include, url
from .forms import CrearCotizacion, ActualizarCotizacion
from .views import ListaCotizaciones
from .views import PdfCreateView
urlpatterns = [

    #url que redirecciona a la pagina de creacion de cotizaciones
    url(r'^cotizacion/crear$', CrearCotizacion.as_view(), name='crear'),
	url(r'^cotizacion/(?P<pk>\d+)/$', ActualizarCotizacion.as_view(), name='actualizar'),
	url(r'^cotizacion/listado$', ListaCotizaciones.as_view(), name='listar'),
	url(r'^cotizacion/PDF/(?P<pk>\d+)/$', PdfCreateView.as_view(), name='pdf'),
]

apps/empleado/models.py
# -*- encoding: utf-8 -*-

from django.db import models
from django.contrib.auth.models import User
from apps.sucursal.models import Sucursal

VENDEDOR = 'Vendedor'
JEFE_TALLER = 'Jefe de taller'
GERENTE = 'Gerente'

tipo_choice = (
	(VENDEDOR, 'Vendedor'),
	(JEFE_TALLER, 'Jefe de taller'),
	(GERENTE, 'Gerente'),
 )

class Empleado(models.Model):
	"""Define la organizacion del los datos de un empleado en la base de datos."""

	#related_name permite hacer una referencia desde user a empleado de la siguiente forma user.empleado
	user = models.OneToOneField(User,related_name='empleado',null=True)
	#Indentificacion del empleado, debe ser unica
	identificacion = models.CharField(max_length=20,unique=True,null=False,blank=True)
	#Direccion de residencia del empleado
	direccion = models.CharField(null=False,blank=True,max_length=200)
	#telefono de residencia del empleado
	telefono = models.CharField(null=False,blank=True,max_length=10)
	#Salario actual del empleado
	salario =  models.BigIntegerField(null=False,blank=True)
	#Sucursal a la que pertenece el empleado
	sucursal = models.ForeignKey(Sucursal,default=None)
	#Imagen o foto del empleado
	#Tipos de empleados que se puden crear
	tipo = models.CharField(null=False,max_length=20, choices=tipo_choice,default=VENDEDOR)
	#Estado de la empleado, Activa/inactiva
	habilitado = models.BooleanField(default = True)
	#Foto de perfil del empleado
	imagen = models.ImageField(null=True,blank=True,upload_to = "imagenes/empleado")

	#Permite hacer modificaciones agregadas a la representacion del modelo
	class Meta:
		ordering = ['identificacion']
		verbose_name_plural = "Empleados"

	#Permite determinar una representacion en string del objeto empleado
	def __str__(self):
		return self.user.first_name

apps/empleado/forms.py
# -*- coding: utf-8 -*-
from django import forms
from .models import *
from django.forms.extras.widgets import *
from django.contrib.auth.forms import UserCreationForm
from django.shortcuts import render_to_response
from django.template import RequestContext
from django.http import HttpResponseRedirect
from django.views.generic import TemplateView
from django.contrib import messages
from django.contrib.auth import authenticate,login
from django.core.urlresolvers import reverse

from .models import Empleado
from apps.sucursal.models import Sucursal
from django.contrib.auth.models import User

class UserForm(UserCreationForm):

	first_name = forms.CharField(label='Nombre')
	last_name = forms.CharField(label='Apellido')
	username = forms.CharField(label='Nombre de Usuario')
	email = forms.EmailField(label='Correo',required=True)
	password1 = forms.CharField(label='Contraseña',widget=forms.PasswordInput,required=False)
	password2 = forms.CharField(label='Confirmar Contraseña',widget=forms.PasswordInput,required=False)

	class Meta:
		model = User
		fields = ( "username", "email", "first_name", "last_name")

class EmpleadoForm(forms.ModelForm):

	identificacion = forms.CharField(label='Numero de Identificación')
	direccion = forms.CharField(label='Dirección')
	telefono = forms.CharField(label='Teléfono')
	salario= forms.CharField(label='Salario',required=True)

	class Meta:
		model = Empleado
		fields = ['identificacion', 'direccion', 'telefono',
		'salario','sucursal','imagen', 'tipo','habilitado' ]

class EmpleadoCreateView(TemplateView):
	"""Crea un empleado dada una sucursal."""

	def get(self,request,*args,**kwargs):
		"""Despliega el formulario de creacion de
		usuario y empleado para una sucursal.
		"""

		sucursal = Sucursal.objects.get(id=kwargs['spk'])

		user_form = UserForm()
		empleado_form = EmpleadoForm( initial={'sucursal':sucursal.id} )

		forms = [user_form,empleado_form]
		context = {
		'section_title':'Nuevo Empleado',
		'button_text':'Crear',
		'sucursal':sucursal,
		'user_form':user_form,
		'empleado_form':empleado_form }

		return render_to_response(
			'empleado/empleado_form.html',
			context,
			context_instance=RequestContext(request))

	def post(self,request,*args,**kwargs):
		user_form = UserForm(request.POST)
		empleado_form = EmpleadoForm(request.POST,request.FILES)

		if user_form.is_valid() and empleado_form.is_valid():
			new_user = user_form.save()
			new_empleado = empleado_form.save()
			new_empleado.user = new_user
			new_empleado.save()
			messages.info(request,'Nuevo empleado creado con exito')

			url = reverse(
				'empleado:listar-empleados-sucursal',
				kwargs={'spk': new_empleado.sucursal.id})

			return HttpResponseRedirect(url)


		sucursal = Sucursal.objects.get(id=kwargs['spk'])
		user_form = UserForm(request.POST)
		empleado_form = EmpleadoForm(request.POST)


		messages.error(request,'Hay errores en algun campo, revise el formulario')

		context = {
		'section_title':'Nuevo Empleado',
		'sucursal':sucursal,
		'user_form':user_form,
		'empleado_form':empleado_form }

		return render_to_response(
			'empleado/empleado_form.html',
			context,
			context_instance=RequestContext(request))


class EmpleadoUpdateView(TemplateView):

	def get(self, request, *args, **kwargs):

		empleado = Empleado.objects.get(id=kwargs['epk'])
		sucursal = Sucursal.objects.get(id=empleado.sucursal.id)
		user = empleado.user

		empleado_form = EmpleadoForm(instance=empleado)
		user_form = UserForm(instance=user)

		context = {
		'section_title':'Actualizar Empleado',
		'sucursal':sucursal,
		'user_form':user_form,
		'empleado_form':empleado_form }

		return render_to_response(
			'empleado/empleado_form.html',
			context,
			context_instance=RequestContext(request))

	def post(sel, request, *args, **kwargs):
		empleado = Empleado.objects.get(id=kwargs['epk'])
		sucursal = Sucursal.objects.get(id=empleado.sucursal.id)
		user = empleado.user

		empleado_form = EmpleadoForm(request.POST,request.FILES,instance=empleado)
		user_form = UserForm(request.POST,request.FILES,instance=user)

		if user_form.is_valid() and empleado_form.is_valid():

			empleado.identificacion = empleado_form.cleaned_data['identificacion']
			empleado.direccion = empleado_form.cleaned_data['direccion']
			empleado.telefono = empleado_form.cleaned_data['telefono']
			empleado.salario = empleado_form.cleaned_data['salario']
			empleado.sucursal = empleado_form.cleaned_data['sucursal']
			empleado.imagen = empleado_form.cleaned_data['imagen']
			empleado.tipo = empleado_form.cleaned_data['tipo']
			empleado.habilitado = empleado_form.cleaned_data['habilitado']
			empleado.save()

			user.username = user_form.cleaned_data['username']
			user.first_name = user_form.cleaned_data['first_name']
			user.last_name = user_form.cleaned_data['last_name']
			user.email = user_form.cleaned_data['email']

			password1 = user_form.cleaned_data['password1']
			password2 = user_form.cleaned_data['password2']

			if password1 != "" and password2 != "":
				user.set_password(user_form.cleaned_data['password1'])
			user.save()

			#En caso de que el gerente este modificando su misma cuenta de empleado,
			#es necesario que vuelva a ser logeado con los nuevos datos username
			#y password
			if user.id == request.user.id:
				user = authenticate(username=user.username,password=password1)
				if user is not None:
					if user.is_active:
						login(request,user)

			messages.info(request,'Empleado modificado con exito')

			url = reverse(
				'empleado:listar-empleados-sucursal',
				kwargs={'spk': sucursal.id})

			return HttpResponseRedirect(url)

		else:
			empleado_form = EmpleadoForm(request.POST,request.FILES)
			user_form = UserForm(instance=user)

			context = {
			'section_title':'Actualizar Empleado',
			'sucursal':sucursal,
			'user_form':user_form,
			'empleado_form':empleado_form }

			return render_to_response(
				'empleado/empleado_form.html',
				context,
				context_instance=RequestContext(request))

apps/empleado/views.py
# -*- encoding: utf-8 -*-

from django.shortcuts import render_to_response
from django.template import RequestContext
from django.views.generic import TemplateView

from .models import Empleado
from apps.sucursal.models import Sucursal



class EmpleadoListView(TemplateView):

	def get(self,request,*args,**kwargs):
		sucursal_id = kwargs['spk']
		empleados = Empleado.objects.filter(sucursal_id=sucursal_id).exclude(user_id=request.user.id)
		sucursal = Sucursal.objects.get(id=sucursal_id)
		context = {
		'sucursal':sucursal,
		'empleados':empleados}
		return render_to_response(
			'empleado/empleado_list.html',
			context,
			RequestContext(request))

apps/empleado/templates/empleado/empleado_form.html
{% extends "base.html" %}
{% load staticfiles %}

{# Load the tag library #}
{% load bootstrap3 %}

{# Load CSS and JavaScript #}
{% bootstrap_javascript %}

{# Display django.contrib.messages as Bootstrap alerts #}
{% bootstrap_messages %}

{% block css %}
{{ block.super }}
    <!-- ================== BEGIN PAGE LEVEL STYLE ================== -->
    <link href="{% static 'color_admin/assets/plugins/bootstrap-wizard/css/bwizard.min.css' %}" rel="stylesheet" />
    <!-- ================== END PAGE LEVEL STYLE ================== -->
{% endblock %}

{% block breadcrumb %}Sucursal {{ sucursal.nombre }}{% endblock %}
{% block section_title %}{{ section_title }}{% endblock %}
{% block section_subtitle %}Por favor diligencie el siguiente formulario{% endblock %}
{% block content %}
            <!-- begin row -->
            <div class="row">
                <!-- begin col-12 -->
                <div class="col-md-12">
                    <form method="post" data-parsley-validate="true" name="form-wizard" enctype="multipart/form-data"> {% csrf_token %}
                        <!-- begin panel -->
                        <div class="panel panel-inverse">
                            <div class="panel-heading">
                                <div class="panel-heading-btn">
                                    <a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-default" data-click="panel-expand"><i class="fa fa-expand"></i></a>
                                    <a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-success" data-click="panel-reload"><i class="fa fa-repeat"></i></a>
                                    <a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-warning" data-click="panel-collapse"><i class="fa fa-minus"></i></a>
                                    <a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-danger" data-click="panel-remove"><i class="fa fa-times"></i></a>
                                </div>
                                <h4 class="panel-title">Empleado</h4>
                            </div>
                            <div class="panel-body">
                                <div id="wizard">
                                    <ol>
                                        <li>
                                            Informacion de la Cuenta
                                            <small>Diligencie los diguientes campos con los datos de usuario.</small>
                                        </li>
                                        <li>
                                            Informacion Adicional
                                            <small>Diligencie los siguientes datos con los datos adicionales.</small>
                                        </li>
                                    </ol>
                                    <!-- begin wizard step-1 -->
                                    <div class="wizard-step-1">
                                        <fieldset>
                                            <!-- begin row -->
                                            <div class="row">
                                              <div class="col-md-8 col-md-offset-2">
                                                  {% bootstrap_form user_form  %}
                                                  <div class="pull-right" >

                                                  </div>
                                              </div>
                                            </div>
                                            <!-- end row -->
                                        </fieldset>
                                    </div>
                                    <!-- end wizard step-1 -->
                                    <!-- begin wizard step-2 -->
                                    <div class="wizard-step-2">
                                        <fieldset>
                                            <!-- begin row -->
                                            <div class="row">
                                              <div class="col-md-8 col-md-offset-2">
                                                  {% bootstrap_form empleado_form %}
                                                  <div class="pull-right" >
                                                    <button type="submit" class="btn btn-sm btn-success m-r-5"><i class="fa fa-cog"></i> Guardar</button>
                                                  </div>
                                              </div>
                                            </div>
                                            <!-- end row -->
                                        </fieldset>
                                    </div>
                                    <!-- end wizard step-2 -->
                                </div>
                            </div>
                        </div>
                        <!-- end panel -->
                    </form>
                </div>
                <!-- end col-12 -->
            </div>
{% endblock %}

{% block javascript %}
{{ block.super }}
<!-- ================== BEGIN PAGE LEVEL JS ================== -->
<script src="{% static 'color_admin/assets/plugins/parsley/dist/parsley.js' %}"></script>
<script src="{% static 'color_admin/assets/plugins/bootstrap-wizard/js/bwizard.js' %}"></script>
<script src="{% static 'color_admin/assets/js/form-wizards-validation.demo.min.js' %}"></script>
<!-- ================== END PAGE LEVEL JS ================== -->
<script>
    $(document).ready(function() {
        FormWizardValidation.init();
    });
</script>
{% endblock %}

apps/empleado/templates/empleado/empleado_list.html
{% extends "base.html" %}
{% load staticfiles %}

{% block css %}
{{ block.super }}
<!-- ================== BEGIN PAGE LEVEL STYLE TABLE================== -->
    <link href="{% static 'color_admin/assets/plugins/DataTables-1.9.4/css/data-table.css' %}" rel="stylesheet" />
    <!-- ================== END PAGE LEVEL STYLE ================== -->
{% endblock %}

{% block breadcrumb %}Sucursal {{ sucursal.nombre }}{% endblock %}
{% block section_title %}Empleados{% endblock %}
{% block section_subtitle %}Seleccione un elemento para modificar su información{% endblock %}
{% block content %}
                <!-- begin col-12 -->
                <div class="col-md-12">

                    <div class="email-btn-row hidden-xs">
                        <a href="{% url 'empleado:crear' sucursal.id %}" class="btn btn-sm btn-success"><i class="fa fa-plus m-r-5"></i> Nuevo empleado</a>
                    </div>

                    <!-- begin panel -->
                    <div class="panel panel-inverse">
                        <div class="panel-heading">
                            <div class="panel-heading-btn">
                                <a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-default" data-click="panel-expand"><i class="fa fa-expand"></i></a>
                                <a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-success" data-click="panel-reload"><i class="fa fa-repeat"></i></a>
                                <a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-warning" data-click="panel-collapse"><i class="fa fa-minus"></i></a>
                                <a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-danger" data-click="panel-remove"><i class="fa fa-times"></i></a>
                            </div>
                            <h4 class="panel-title">Empleados </h4>
                        </div>
                        <div class="panel-body">
                            <div class="table-responsive">
                                <table id="data-table" class="table table-striped table-bordered">
                                    <thead>
                                        <tr>
                                            <th>Nombre de usuario</th>
                                            <th>Primer Nombre</th>
                                            <th>Segundo Nombre</th>
                                            <th>Ultimo Login</th>
                                            <th>Identificacion</th>
                                            <th>Direccion</th>
                                            <th>Telefono</th>
                                            <th>Salario</th>
                                            <th>Sucursal</th>
                                            <th>Tipo</th>
                                            <th>Habilitado</th>
                                            <th>Foto Perfil</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        {% for empleado  in empleados %}
                                            <tr>
                                                <td><a href="{% url 'empleado:actualizar' empleado.id %}"> {{ empleado.user.username }}</a></td>
                                                <td>{{ empleado.user.first_name }}</td>
                                                <td>{{ empleado.user.last_name }}</td>
                                                <td>{{ empleado.user.last_login }}</td>
                                                <td>{{ empleado.identificacion }}</td>
                                                <td>{{ empleado.direccion }}</td>
                                                <td>{{ empleado.telefono }}</td>
                                                <td>{{ empleado.salario }}</td>
                                                <td>{{ empleado.sucursal }}</td>
                                                <td>{{ empleado.tipo }}</td>
                                                <td>{% if empleado.habilitado %}
                                                    <ul class="fa-ul">
                                                        <li><i class="fa-li fa fa-check-square text-success"></i></li>
                                                    </ul>
                                                    {% else %}
                                                    <ul class="fa-ul">
                                                        <li><i class="fa-li fa fa-square"></i></li>
                                                    </ul>
                                                    {% endif %}
                                                </td>
                                                <td>{% if  empleado.imagen %}
                                                    <img src={{ empleado.imagen.url }} width=50 height=50 class="media-object rounded-corner" />
                                                    {% else %}
                                                    <img src="{{ MEDIA_URL }}imagenes/empleado/imagen_no_disponible.png" width=50 height=50 class="media-object rounded-corner" />
                                                    {% endif %}
                                                </td>
                                            </tr >
                                        {% endfor %}
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                    <!-- end panel -->
                </div>
                <!-- end col-12 -->

{% endblock %}

{% block javascript %}
{{ block.super }}
    <!-- ================== BEGIN PAGE LEVEL JS TABLE ================== -->
    <script src="{% static 'color_admin/assets/plugins/DataTables-1.9.4/js/jquery.dataTables.js' %}"></script>
    <script src="{% static 'color_admin/assets/plugins/DataTables-1.9.4/js/data-table.js' %}"></script>
    <script src="{% static 'color_admin/assets/js/inbox.demo.min.js' %}"></script>
    <!-- ================== END PAGE LEVEL JS ================== -->
{% endblock %}