ProMotos/urls.py
# -*- encoding: utf-8 -*-
from django.contrib import admin
from django.conf.urls import include, url
from ProMotos import settings
admin.autodiscover()

urlpatterns = [
	url(r'^admin/', include(admin.site.urls)),
	url(r'', include('apps.home.urls',namespace='inicio')),
	url(r'', include('apps.cuenta.urls',namespace='cuenta')),
    url(r'', include('apps.cotizacion.urls',namespace='cotizacion')),
    url(r'', include('apps.cliente.url',namespace='cliente')),
    url(r'', include('apps.empleado.url',namespace='empleado')),
    url(r'', include('apps.repuesto.url',namespace='repuesto')),
    url(r'', include('apps.sucursal.url',namespace='sucursal')),
    url(r'', include('apps.motocicleta.url',namespace='motocicleta')),
    url(r'', include('apps.venta.url',namespace='venta')),
    url(r'', include('apps.proveedor.url',namespace='proveedor')),
    url(r'', include('apps.reporte.url',namespace='reporte')),
    url(r'', include('apps.orden_de_trabajo.url',namespace='orden_de_trabajo')),
    url(r'', include('apps.cotizacion_orden_de_trabajo.url',namespace='cotizacion_orden_de_trabajo')),
    url(r'', include('apps.factura_orden_de_trabajo.url',namespace='factura_orden_de_trabajo')),
    url(r'', include('apps.movil.url',namespace='movil')),
]

apps/cotizacion/urls.py
# -*- encoding: utf-8 -*-

from django.conf.urls import include, url
from .forms import CrearCotizacion, ActualizarCotizacion
from .views import ListaCotizaciones
from .views import PdfCreateView
urlpatterns = [

    #url que redirecciona a la pagina de creacion de cotizaciones
    url(r'^cotizacion/crear$', CrearCotizacion.as_view(), name='crear'),
	url(r'^cotizacion/(?P<pk>\d+)/$', ActualizarCotizacion.as_view(), name='actualizar'),
	url(r'^cotizacion/listado$', ListaCotizaciones.as_view(), name='listar'),
	url(r'^cotizacion/PDF/(?P<pk>\d+)/$', PdfCreateView.as_view(), name='pdf'),
]

apps/sucursal/models.py
# -*- encoding: utf-8 -*-

from django.db import models
from apps.motocicleta.models import Motocicleta
from apps.repuesto.models import Repuesto

class Sucursal(models.Model):
	"""Define la organizacion de los datos de una sucursal en la base de datos"""

	#Django por defecto, cuando los modelos no tienen primary_key, coloca una llamada "id"

	#Nombre de la sucursal
	nombre = models.CharField(null=True,blank=True,max_length=20,unique=True)
	#Direccion en la cual queda ubicada la sucursal
	direccion = models.CharField(null=True,blank=True,max_length=50)
	#Telefono de la sucursal
	telefono = models.CharField(null=True,blank=True,max_length=10)
	#Ciudad donde queda ubicada la sucursal
	ciudad = models.CharField(null=True,blank=True,max_length = 50)
	#Estado de la sucursa, Activa/inactiva
	habilitado = models.BooleanField(default = True)
	#Vehiculos que tiene la sucursal en venta
	#related_name para poder acceder desde una instancia vehiculo a su sucursal
	motocicletas = models.ManyToManyField(Motocicleta,through='Sucursal_Motocicleta',related_name='sucursal')
	#Repuestos que tiene la sucursal
	#related_name para poder acceder desde una instancia repuesto a su sucursal
	repuestos = models.ManyToManyField(Repuesto,through='SucursalRepuesto',related_name='sucursal')

	#Permite hacer modificaciones agregadas a la representacion del modelo
	class Meta:
		ordering = ['nombre']
		verbose_name_plural = "Sucursales"
		unique_together = ("nombre","ciudad")

	#Permite determinar una representacion en string del objeto empleado
	def __str__(self):
		return self.nombre



class Sucursal_Motocicleta(models.Model):
	"""Define la cantidad que existe de cada vehiculo por sucursal."""

	#Sucursal a la que pertenece el vehiculo
	sucursal = models.ForeignKey(Sucursal,default=None)
	#Vehiculo
	motocicletas = models.ForeignKey(Motocicleta,default=None)
	#Color del vehiculo
	color = models.CharField(null=True,blank=True,max_length=20)
	#Cantidad disponible en stock del repuesto en la sucursal
	cantidad = models.IntegerField(null=True,blank=True)
	#Estado de la vehiculo, Activa/inactiva
	habilitado = models.BooleanField(default=True)

	class Meta:
		ordering = ['cantidad']
		verbose_name_plural = 'Motocicletas Sucursal'
		unique_together = ("sucursal", "motocicletas", "color")

	def __str__(self):
		return self.motocicletas.marca + " " + self.motocicletas.modelo + " " + self.color

	def nombre_sucursal(self):
		return self.sucursal.nombre

	def numero_serie(self):
		return self.motocicletas.numero_serie

	def color_vehiculo(self):
		return self.color

	def marca_vehiculo(self):
		return sefl.vehiculo.marca

	def cantidad_vehiculo(self):
		return self.cantidad


class SucursalRepuesto(models.Model):
	"""Define la cantidad que existe de cada repuesto por sucursal."""

	#Sucursal a la que pertenece el repuesto
	sucursal = models.ForeignKey(Sucursal,default=None)
	#Repuesto
	repuesto = models.ForeignKey(Repuesto,default=None)
	#Cantidad disponible en stock del repuesto en la sucursal
	cantidad = models.IntegerField(null=True,blank=True)
	#Estado de la repuesto, Activa/inactiva
	habilitado = models.BooleanField(default = True)

	def nombre_sucursal(self):
		return self.sucursal.nombre

	def nombre_repuesto(self):
		return self.repuesto.nombre

	def cantidad_repuesto(self):
		return self.cantidad

	class Meta:
		ordering = ['cantidad']
		verbose_name_plural = 'Repuestos Sucursal'
		unique_together = ("sucursal", "repuesto")

	#Permite determinar una representacion en string del objeto SucursalRepuesto
	def __str__(self):
		return self.sucursal.nombre + " " + self.repuesto.nombre

apps/sucursal/forms.py
# -*- encoding: utf-8 -*-

from django.core.urlresolvers import reverse_lazy, reverse
from django.views.generic.edit import CreateView, UpdateView
from django.views.generic import TemplateView
from django.http import HttpResponse
from django.template import loader
from django.template import Context
from django import forms

from .models import Sucursal

import json

class SucursalCreateForm(forms.ModelForm):
	class Meta:
		model = Sucursal
		fields = ('nombre', 'direccion', 'telefono', 'ciudad','habilitado')


class SucursalAjaxCreateView(TemplateView):

	def get(self,request,*args,**kwargs):
		template = loader.get_template('sucursal/includes/form.html')
		form = SucursalCreateForm()
		context = {'form':form}
		html = template.render(context)
		response = {
			'status':True,
			'html':html
		}
		data = json.dumps(response)
		return HttpResponse(data,content_type='application/json')

	
	def post(self,request,*args,**kwargs):
		form = SucursalCreateForm(request.POST)
		if form.is_valid():
			form.save()
			template = loader.get_template('sucursal/includes/tabla.html')
			context = {'sucursales':Sucursal.objects.all()}
			html = template.render(context)
			response = {
				'status':True,
				'html':html
			}
			data = json.dumps(response)
			return HttpResponse(data,content_type='application/json')
		
		template = loader.get_template('sucursal/includes/form.html')
		context = {'form':form}
		html = template.render(context)
		response = {
			'status':False,
			'html':html
		}
		data = json.dumps(response)
		return HttpResponse(data,content_type='application/json')
			

class SucursalAjaxUpdateView(TemplateView):

	def get(self,request,*args,**kwargs):
		template = loader.get_template('sucursal/includes/form.html')
		sucursal = Sucursal.objects.get(id=kwargs['pk'])
		form = SucursalCreateForm(instance=sucursal)
		context = {'form':form}
		html = template.render(context)
		response = {
			'status':True,
			'html':html
		}
		data = json.dumps(response)
		return HttpResponse(data,content_type='application/json')

	
	def post(self,request,*args,**kwargs):
		sucursal = Sucursal.objects.get(id=kwargs['pk'])
		form = SucursalCreateForm(request.POST,instance=sucursal)
		if form.is_valid():
			form.save()
			template = loader.get_template('sucursal/includes/tabla.html')
			context = {'sucursales':Sucursal.objects.all()}
			html = template.render(context)
			response = {
				'status':True,
				'html':html
			}
			data = json.dumps(response)
			return HttpResponse(data,content_type='application/json')
		
		template = loader.get_template('sucursal/includes/form.html')
		context = {'form':form}
		html = template.render(context)
		response = {
			'status':False,
			'html':html
		}
		data = json.dumps(response)
		return HttpResponse(data,content_type='application/json')

apps/sucursal/views.py
# -*- encoding: utf-8 -*-

from django.views.generic import ListView 
from django.views.generic.detail import DetailView 
from .models import Sucursal 
from .forms import SucursalCreateForm

class SucursalesListView(ListView): 
	"""Lista todas las sucursales de la base de datos."""
	model = Sucursal
	context_object_name = 'sucursales'
	template_name = 'sucursal/list.html'

	def get_context_data(self,**kwargs):
		context = super(SucursalesListView,self).get_context_data(**kwargs)
		return context

apps/sucursal/templates/sucursal/includes/form.html
{# Load the tag library #}
{% load bootstrap3 %}

{# Load CSS and JavaScript #}
{% bootstrap_javascript %}

{# Display django.contrib.messages as Bootstrap alerts #}
{% bootstrap_messages %}

{% bootstrap_form form %}

apps/sucursal/templates/sucursal/includes/tabla.html
                      <div class="col-md-12">
                        <!-- begin panel -->
                        <div class="panel panel-inverse">
                            <div class="panel-heading">
                                <div class="panel-heading-btn">
                                    <a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-default" data-click="panel-expand"><i class="fa fa-expand"></i></a>
                                    <a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-warning" data-click="panel-collapse"><i class="fa fa-minus"></i></a>
                                </div>
                                <h4 class="panel-title">Sucursales</h4>
                            </div>
                            <div class="panel-body">
                                <div class="table-responsive">
                                    <table class="table table-striped table-bordered">
                                        <thead>
                                            <tr>
                                                <th>Nombre</th>
                                                <th>Dirección</th>
                                                <th>Telefono</th>
                                                <th>Ciudad</th>
                                                <th>Activo</th>
                                                <th>Empleados</th>
                                                <th>Vehiculos</th>
                                                <th>Repuestos</th>
                                                <th>Orden de Trabajo</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            {% for sucursal  in sucursales %}
                                                <tr>
                                                    <td >
                                                        <a class="update" href="{% url 'sucursal:actualizar' sucursal.pk %}">
                                                        {{ sucursal.nombre }}
                                                        </a>
                                                    </td>
                                                    <td>{{ sucursal.direccion }}</td>
                                                    <td>{{ sucursal.telefono }}</td>
                                                    <td>{{ sucursal.ciudad }}</td>
                                                    <td>
                                                        {% if sucursal.habilitado %}
                                                        <ul class="fa-ul">
                                                            <li><i class="fa-li fa fa-check-square text-success"></i></li>
                                                        </ul>
                                                        {% else %}
                                                        <ul class="fa-ul">
                                                            <li><i class="fa-li fa fa-square"></i></li>
                                                        </ul>
                                                        {% endif %}
                                                    <td>
                                                        <a href="{% url 'empleado:listar-empleados-sucursal' sucursal.id %}">
                                                            <button type="button" class="btn btn-info btn-xs"><i class="fa fa-cog"></i> Administrar</button>
                                                        </a>
                                                    </td>
                                                    <td>
                                                        <a href="{% url 'vehiculo:listar-vehiculos-sucursal' sucursal.id %}">
                                                            <button type="button" class="btn btn-xs btn-success m-r-5"><i class="fa fa-edit"></i> Inventario</button>
                                                        </a>
                                                    </td>
                                                    <td>
                                                        <a href="{% url 'repuesto:listar-repuestos-sucursal' sucursal.id %}">
                                                            <button type="button" class="btn btn-xs btn-warning m-r-5"><i class="fa fa-edit"></i> Inventario</button>
                                                        </a>
                                                    </td>
                                                    <td>
                                                        <div class="btn-group btn-xs">
                                                            <a href="javascript:;" data-toggle="dropdown" class="btn btn-white dropdown-toggle btn-xs">Opciones <span class="caret"></span></a>
                                                            <ul class="dropdown-menu">
                                                                <li>
                                                                    <a href="{% url 'cotizacion_orden_de_trabajo:listar' sucursal.pk %}">
                                                                        Cotizaciones
                                                                    </a>
                                                                </li>
                                                                <li>
                                                                    <a href="{% url 'factura_orden_de_trabajo:listar' sucursal.pk %}">
                                                                        Facturas
                                                                    </a>
                                                                </li>
                                                            </ul>
                                                        </div>
                                                    </td>
                                                </tr >
                                            {% endfor %}
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                        <!-- end panel -->
                      </div>